name: Primary

on:
  push:
    branches:
      - main # deployed to development
    tags:
      - v* # release tags → production

  pull_request:
    branches:
      - main # run on PRs targeting main

jobs:
  # define's SSM_NAMESPACE / STACK_NAME consistently
  context:
    uses: fromtheforest-io/github-actions/.github/workflows/context.yml@main
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
    with:
      service_name: hosted-zone

  # deploy:
  #   if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   needs:
  #     - context

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4.1.7
